/** This file is auto-generated by Plasmic; please do not edit! */

import '../scripts/globals.js';
import * as React from 'react';
import PlasmicLoader from '@plasmicapp/loader';

export default function PageComponent() {
    return <PlasmicLoader projectId="tbwSPDBh94zbu5WULbgVc3" component="Projects"  />
}